### PR TITLE
Feature/ssh creds by user

### PR DESCRIPTION
**Pull request by terabyte**
This is my full rewrite of SSH key auth.  It should "just work".

* A new authentication mode is included which uses SSH auth
* At plugin startup, a master SSH key is generated and stored in the DB
* At the time you save a server config, that user is created and the public ssh key is added to it
* At the time you save a repository config, the credential for that username is added to jenkins if it does not exist and the generated jenkins job is configured to use it.

The only piece of junk you have to deal with outside of stashbot itself is ensuring there are no conflicting entries in ~/.ssh/known_hosts, or your jobs will fail to clone with errors.

There are two possible migration paths to upgrade:
1. Install new stashbot, upgrade jenkins git plugins, change jenkins server config to use ssh, resave all repository configs.
2. Set up a new jenkins server running the newest git plugin, upgrade stashbot, create new jenkins server configuration using ssh mode, migrate repos over one-by-one to use the other jenkins server, spin down the other one

1 is ripping the bandaid off, 2 is incremental and making sure you don't break the crap out of everything.  I don't envy you guys on this one.  But it is the only way to get the future (and not fragile jenkins).

Anyways, please review the code and see what you think or if you want any changes before merging it in.  Many thanks!
-Carl

### CODE REVIEW

**Comment by terabyte** [comment]
@alexander-87 - If you still want something to beta-test, this version should be "working".

**Comment by alexander-87** [comment]
Hi Carl,

I just tried running 9f3da81 on a local instance of Stash using the SDK and I received the following error when attempting to start Stash via the `atlas-run` command:

    Downloading: file://C:\Users\ALEXANDER\atlassian-plugin-sdk/repository/com/offbytwo/jenkins/jenkins-client/0.3.1-SNAPSHOT/jenkins-client-0.3.1-SNAPSHOT.jar
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 55.475 s
    [INFO] Finished at: 2015-06-30T16:08:30-06:00
    [INFO] Final Memory: 21M/334M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal on project stashbot: Could not resolve dependencies for project com.palantir.stash:stashbot:atlassian-plugin:0.0.1-DEV: Could not find artifact com.offbytwo.jenkins:jenkins-client:jar:0.3.1-SNAPSHOT in atlassian-public (https://maven.atlassian.com/repository/public) -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

I'm relatively new to Java *(I'm more of a .NET guy)*, so I might be overlooking something simple here.

**Comment by terabyte** [comment]
@alexander-87 sorry about this - I should have been more clear.  That commit depends upon a custom version of the jenkins-client library, but it isn't bundled in "yet".  You need a later commit (d8b2c88).  I would go ahead and check out the latest commit (9e3fb0c) because it also has docs and test resources.  If you run a build of that, it should "just work".  Let me know if that does it for you.

Thanks!
-Carl

**Comment by alexander-87** [comment]
@terabyte thanks for the clarification! I was able to get everything up & running with commit 9e3fb0c.

Everything seems to be working great so far, although I haven't had time yet to do anything more than just a few basic tests. I'm planning on doing more testing next week, and I'll let you if I find any issues.

**Comment by terabyte** [comment]
This got closed because I did some branch renaming/shuffling in my fork.  This branch is stale and you should actually pull my master branch.  I've taken most of davidk's changes (like the one that removes the trigger PR link if stashbot is not enabled on that repo) but not the psql one (because we don't understand what is going on there yet).

**Pull request closed without merging**
