### PR TITLE
fixing PSQLException error

### PR DESCRIPTION
**Pull request by davidk01**
Seeing intermittent error

```
org.postgresql.util.PSQLException: ERROR: cannot execute nextval() in a read-only transaction
at com.atlassian.activeobjects.internal.EntityManagedActiveObjects.create(EntityManagedActiveObjects.java:113) ~[na:na]
at com.atlassian.activeobjects.osgi.TenantAwareActiveObjects.create(TenantAwareActiveObjects.java:299) ~[na:na]
at com.palantir.stash.stashbot.config.ConfigurationPersistenceImpl.getPullRequestMetadata(ConfigurationPersistenceImpl.java:481) ~[na:na]
at com.palantir.stash.stashbot.config.ConfigurationPersistenceImpl.getPullRequestMetadata(ConfigurationPersistenceImpl.java:462) ~[na:na]
at com.atlassian.activeobjects.tx.TransactionalProxy.invoke(TransactionalProxy.java:79) ~[na:na]
...
```

Internet seems to think this has something to do with multiple transactions not executing properly: http://stackoverflow.com/questions/3672219/hibernate-error-current-transaction-is-aborted-commands-ignored-until-end-of-t.

Adding retry logic should in theory fix it when there are competing transactions happening.

### CODE REVIEW

**Comment by terabyte** [comment]
I'm a little skeptical about this - in particular, have you seen a failure that corrected itself on a retry?  Because of the way stash is written, if you start out in a read-only transaction, your code will stay in it (because it wraps the entire entry point) I think.  @bturner might have thoughts on this...

**Comment by terabyte** [comment]
I'll try to find time to look into it soon too

**Comment by terabyte** [comment]
notice in other places, I move some DB operations into other "entry points" to avoid being in a read-only transaction (like the listeners that vivify rows in the metadata table during PR creation so they don't instead happen while rendering a pull request view, which is a read-only transaction)

**Comment by davidk01** [comment]
You mean retries in DB transactions in general? Yes, I have indeed seen transaction failures fix themselves after a sleep and a retry. That's why I added the same logic here. I don't really know how often or in which circumstances this actually occurs. The internal jira ticket indicates it is intermittent and not reproducible which points to transaction contention and the usual fix is a re-try.

**Comment by terabyte** [comment]
in that case, you might be right about this instance of the problem.

**Comment by bturner** [comment]
Apologies for the delay in reviewing this.

I wouldn't apply this change, personally, without some additional details. Can you post the _full stack trace_, including all "caused by" entries, for the error? The snippet in the description is cut off far too early to show useful information. I'd like to see the full stack, and the thread name if it's available. If the error has happened multiple times, logging from multiple occurrences would really help confirm the issue.

**Comment by nebkor** [comment]
@bturner I apologize for the delay in getting you this, but here's what we have in terms of stacktrace:
```
org.postgresql.util.PSQLException: ERROR: cannot execute nextval() in a read-only transaction

        at com.atlassian.activeobjects.internal.EntityManagedActiveObjects.create(EntityManagedActiveObjects.java:113) ~[na:na]

        at com.atlassian.activeobjects.osgi.TenantAwareActiveObjects.create(TenantAwareActiveObjects.java:299) ~[na:na]

        at com.palantir.stash.stashbot.config.ConfigurationPersistenceImpl.getPullRequestMetadata(ConfigurationPersistenceImpl.java:481) ~[na:na]

        at com.palantir.stash.stashbot.config.ConfigurationPersistenceImpl.getPullRequestMetadata(ConfigurationPersistenceImpl.java:462) ~[na:na]

        at com.atlassian.activeobjects.tx.TransactionalProxy.invoke(TransactionalProxy.java:79) ~[na:na]

        at com.atlassian.activeobjects.tx.TransactionalProxy.access$000(TransactionalProxy.java:18) ~[na:na]

        at com.atlassian.activeobjects.tx.TransactionalProxy$1.doInTransaction(TransactionalProxy.java:63) ~[na:na]

        at com.atlassian.sal.core.transaction.HostContextTransactionTemplate$1.doInTransaction(HostContextTransactionTemplate.java:25) ~[sal-core-2.13.3.jar:na]

        at com.atlassian.stash.internal.sal.spi.HostContextAccessorImpl.doInTransaction(HostContextAccessorImpl.java:27) ~[stash-platform-3.7.1.jar:na]

        at com.atlassian.sal.core.transaction.HostContextTransactionTemplate.execute(HostContextTransactionTemplate.java:21) ~[sal-core-2.13.3.jar:na]

        at com.atlassian.activeobjects.internal.SalTransactionManager.inTransaction(SalTransactionManager.java:48) ~[na:na]

        at com.atlassian.activeobjects.internal.AbstractLoggingTransactionManager.doInTransaction(AbstractLoggingTransactionManager.java:19) ~[na:na]

        at com.atlassian.activeobjects.internal.EntityManagedActiveObjects.executeInTransaction(EntityManagedActiveObjects.java:276) ~[na:na]

        at com.atlassian.activeobjects.osgi.TenantAwareActiveObjects.executeInTransaction(TenantAwareActiveObjects.java:383) ~[na:na]

        at com.atlassian.activeobjects.tx.TransactionalProxy.executeInTransaction(TransactionalProxy.java:57) ~[na:na]

        at com.atlassian.activeobjects.tx.TransactionalProxy.invokeInTransaction(TransactionalProxy.java:47) ~[na:na]

        at com.atlassian.activeobjects.tx.TransactionalProxy.invoke(TransactionalProxy.java:35) ~[na:na]

        at com.palantir.stash.stashbot.hooks.PullRequestBuildSuccessMergeCheck.check(PullRequestBuildSuccessMergeCheck.java:153) ~[na:na]

        at com.atlassian.stash.internal.pull.DefaultMergeRequestCheckService.doCheck(DefaultMergeRequestCheckService.java:67) [stash-service-impl-3.7.1.jar:na]

        at com.atlassian.stash.internal.pull.DefaultMergeRequestCheckService.checkMergeability(DefaultMergeRequestCheckService.java:52) [stash-service-impl-3.7.1.jar:na]

        at com.atlassian.stash.internal.pull.DefaultPullRequestService.canMerge(DefaultPullRequestService.java:312) [stash-service-impl-3.7.1.jar:na]

        at com.atlassian.stash.internal.rest.pull.PullRequestResource.canMerge(PullRequestResource.java:396) [stash-rest-3.7.1.jar:na]

        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:25) [applinks-plugin-4.3.5_1425365282000.jar:na]

        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:86) [StashAuthenticationFilter.class:na]

        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:111) [BeforeLoginPluginAuthenticationFilter.class:na]

        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:77) [BeforeLoginPluginAuthenticationFilter.class:na]

        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:100) [atlassian-trusted-apps-core-3.0.8.jar:na]

        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:79) [atlassian-oauth-service-provider-plugin-1.9.10_1421879980000.jar:na]

        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:32) [analytics-client-3.56_1421792972000.jar:na]

        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [analytics-client-3.56_1421792972000.jar:na]

        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:89) [BeforeLoginPluginAuthenticationFilter.class:na]

        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [BeforeLoginPluginAuthenticationFilter.class:na]

        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:85) [stash-service-impl-3.7.1.jar:na]

        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) [ConfigurableWebFilter.class:na]

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]

        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]

        ... 375 frames trimmed

Caused by: org.postgresql.util.PSQLException: ERROR: cannot execute nextval() in a read-only transaction

        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198) ~[postgresql-9.3-1102-jdbc41.jar:na]

        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927) ~[postgresql-9.3-1102-jdbc41.jar:na]

        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.3-1102-jdbc41.jar:na]

        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561) ~[postgresql-9.3-1102-jdbc41.jar:na]

        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419) ~[postgresql-9.3-1102-jdbc41.jar:na]

        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304) ~[postgresql-9.3-1102-jdbc41.jar:na]

        at com.jolbox.bonecp.PreparedStatementHandle.executeQuery(PreparedStatementHandle.java:172) ~[bonecp-0.7.1.RELEASE.jar:0.7.1.RELEASE]

        at net.java.ao.db.PostgreSQLDatabaseProvider.insertReturningKey(PostgreSQLDatabaseProvider.java:299) ~[na:na]

        at net.java.ao.EntityManager.create(EntityManager.java:398) ~[na:na]

        at com.atlassian.activeobjects.internal.EntityManagedActiveObjects.create(EntityManagedActiveObjects.java:109) ~[na:na]

        ... 36 common frames omitted
```

**Comment by bturner** [comment]
@nebkor 

Sorry for not responding sooner. That stack trace indicates the `PullRequestBuildSuccessMergeCheck` is trying to create a database entry as part of its processing inside a `PullRequestService.canMerge` call. `canMerge` is run in a read-only transaction, which `PullRequestBuildSuccessMergeCheck` ends up participating in. Hence the error.

Unfortunately, with how `HostContextAccessorImpl.doInTransaction` is implemented in Stash, trying to get a transaction on a thread where a Spring-managed transaction is already active means you don't actually get your own transaction. Your code just runs as part of the transaction that's already open. That's normal Spring behavior, but it trips up plugins from time to time. (I'm lobbying to have that implementation changed, but it's a somewhat risky decision so we're trying to consider the edge cases.)

Either way, what that means is that your call is happening inside the read-only transaction created by `canMerge`. Hence the exception. As @terabyte has indicated, the correct fix here is to move the code that's trying to create that entity onto another thread so that it can get its own transaction. Retrying isn't really a "solution" to this error.

In newer versions of the `MergeRequestCheck` SPI, `MergeRequest` has an `isDryRun()` flag which can be used to differentiate between when the check is running in `PullRequestService.canMerge` or `PullRequestService.merge`. That might be another possible solution here, to modify the check code such that it doesn't try to create entities during `canMerge` checks`. `PullRequestService.merge` is run in a _read-write_ transaction, so creating your entity as part of that transaction would not hit this error.

Best regards,
Bryan Turner
Atlassian Stash

**Comment by nebkor** [comment]
Hi @bturner, thank you so much for the insightful commentary!  Although I merged this already, I'll get a proper fix in soon.

**Pull request merged**
